var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/logistica/inventario/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.mnb4h._.js")
R.c("server/chunks/ssr/05kk_next_dist_0tx1gom._.js")
R.c("server/chunks/ssr/05kk_next_dist_esm_build_templates_app-page_08yvq8b.js")
R.c("server/chunks/ssr/[root-of-the-server]__05bb7z-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bi421v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ag2wy._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_0uqtttd._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_forbidden_0sjco.1.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_unauthorized_0t1cdw3.js")
R.c("server/chunks/ssr/apps_web_app_global-error_tsx_0t11m~q._.js")
R.c("server/chunks/ssr/_08cqv8o._.js")
R.c("server/chunks/ssr/_0~whrju._.js")
R.c("server/chunks/ssr/05kk_next_dist_0glp-rn._.js")
R.c("server/chunks/ssr/09og__next-internal_server_app_dashboard_logistica_inventario_page_actions_0ayguhm.js")
R.m(66285)
module.exports=R.m(66285).exports
