var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/reportes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ws~8tk._.js")
R.c("server/chunks/ssr/05kk_next_dist_0tx1gom._.js")
R.c("server/chunks/ssr/05kk_next_dist_esm_build_templates_app-page_12n_5le.js")
R.c("server/chunks/ssr/[root-of-the-server]__05bb7z-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bi421v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ag2wy._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_0uqtttd._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_forbidden_0sjco.1.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_unauthorized_0t1cdw3.js")
R.c("server/chunks/ssr/apps_web_app_global-error_tsx_0t11m~q._.js")
R.c("server/chunks/ssr/_08cqv8o._.js")
R.c("server/chunks/ssr/_0~whrju._.js")
R.c("server/chunks/ssr/05kk_next_dist_0glp-rn._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_dashboard_reportes_page_actions_05_-6cy.js")
R.m(88889)
module.exports=R.m(88889).exports
