var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/strategy/pricing/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__031fztb._.js")
R.c("server/chunks/ssr/05kk_next_dist_0tx1gom._.js")
R.c("server/chunks/ssr/05kk_next_dist_esm_build_templates_app-page_0jag0bn.js")
R.c("server/chunks/ssr/[root-of-the-server]__05bb7z-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bi421v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ag2wy._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_0uqtttd._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_forbidden_0sjco.1.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_unauthorized_0t1cdw3.js")
R.c("server/chunks/ssr/apps_web_app_global-error_tsx_0t11m~q._.js")
R.c("server/chunks/ssr/_08cqv8o._.js")
R.c("server/chunks/ssr/_0~whrju._.js")
R.c("server/chunks/ssr/05kk_next_dist_0glp-rn._.js")
R.c("server/chunks/ssr/02dz_web__next-internal_server_app_dashboard_strategy_pricing_page_actions_0gqm6k6.js")
R.m(70370)
module.exports=R.m(70370).exports
