// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: "SET NODE_TLS_REJECT_UNAUTHORIZED='0' && ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
