var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(store)/linea/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bjoln2._.js")
R.c("server/chunks/ssr/05kk_next_dist_0tx1gom._.js")
R.c("server/chunks/ssr/05kk_next_dist_esm_build_templates_app-page_10o9_vm.js")
R.c("server/chunks/ssr/[root-of-the-server]__05bb7z-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bi421v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ag2wy._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_0uqtttd._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_forbidden_0sjco.1.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_unauthorized_0t1cdw3.js")
R.c("server/chunks/ssr/apps_web_app_global-error_tsx_0t11m~q._.js")
R.c("server/chunks/ssr/apps_web_app_(store)_layout_tsx_0ajsdfs._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_(store)_linea_[slug]_page_actions_13m8d0n.js")
R.m(11243)
module.exports=R.m(11243).exports
