// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/b2b" | "/beneficios" | "/catalog" | "/catalog/[slug]" | "/checkout" | "/checkout/confirmacion" | "/corporativo" | "/dashboard" | "/dashboard/audit" | "/dashboard/b2b" | "/dashboard/compras/facturacion" | "/dashboard/compras/recepcion" | "/dashboard/conocimiento" | "/dashboard/customers" | "/dashboard/finanzas" | "/dashboard/finanzas/cash-flow" | "/dashboard/finanzas/nomina" | "/dashboard/finanzas/opex" | "/dashboard/logistica/envios" | "/dashboard/logistica/insumos" | "/dashboard/logistica/inventario" | "/dashboard/logistica/inventario/salidas-no-comerciales" | "/dashboard/logistica/proveedores" | "/dashboard/orders" | "/dashboard/orders/new" | "/dashboard/personalizaciones" | "/dashboard/personalizaciones/nueva" | "/dashboard/pqrs" | "/dashboard/products" | "/dashboard/products/[id]/edit" | "/dashboard/products/new" | "/dashboard/reportes" | "/dashboard/settings" | "/dashboard/settings/users" | "/dashboard/strategy/pricing" | "/envios" | "/forgot-password" | "/legal/cookies" | "/legal/data-processing" | "/legal/privacy" | "/linea/[slug]" | "/lineas" | "/login" | "/personaliza" | "/personaliza/configurador" | "/pqrs" | "/profile" | "/register" | "/reset-password"
type AppRouteHandlerRoutes = "/api/proxy/[...path]" | "/api/v1/[...path]" | "/auth/signout"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/legal"
type RedirectRoutes = "/dashboard/compras/proveedores" | "/dashboard/finance" | "/dashboard/finance/cash-flow" | "/dashboard/finance/opex" | "/dashboard/logistics/inventory" | "/dashboard/logistics/suppliers"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/proxy/[...path]": { "path": string[]; }
  "/api/v1/[...path]": { "path": string[]; }
  "/auth/signout": {}
  "/b2b": {}
  "/beneficios": {}
  "/catalog": {}
  "/catalog/[slug]": { "slug": string; }
  "/checkout": {}
  "/checkout/confirmacion": {}
  "/corporativo": {}
  "/dashboard": {}
  "/dashboard/audit": {}
  "/dashboard/b2b": {}
  "/dashboard/compras/facturacion": {}
  "/dashboard/compras/proveedores": {}
  "/dashboard/compras/recepcion": {}
  "/dashboard/conocimiento": {}
  "/dashboard/customers": {}
  "/dashboard/finance": {}
  "/dashboard/finance/cash-flow": {}
  "/dashboard/finance/opex": {}
  "/dashboard/finanzas": {}
  "/dashboard/finanzas/cash-flow": {}
  "/dashboard/finanzas/nomina": {}
  "/dashboard/finanzas/opex": {}
  "/dashboard/logistica/envios": {}
  "/dashboard/logistica/insumos": {}
  "/dashboard/logistica/inventario": {}
  "/dashboard/logistica/inventario/salidas-no-comerciales": {}
  "/dashboard/logistica/proveedores": {}
  "/dashboard/logistics/inventory": {}
  "/dashboard/logistics/suppliers": {}
  "/dashboard/orders": {}
  "/dashboard/orders/new": {}
  "/dashboard/personalizaciones": {}
  "/dashboard/personalizaciones/nueva": {}
  "/dashboard/pqrs": {}
  "/dashboard/products": {}
  "/dashboard/products/[id]/edit": { "id": string; }
  "/dashboard/products/new": {}
  "/dashboard/reportes": {}
  "/dashboard/settings": {}
  "/dashboard/settings/users": {}
  "/dashboard/strategy/pricing": {}
  "/envios": {}
  "/forgot-password": {}
  "/legal": {}
  "/legal/cookies": {}
  "/legal/data-processing": {}
  "/legal/privacy": {}
  "/linea/[slug]": { "slug": string; }
  "/lineas": {}
  "/login": {}
  "/personaliza": {}
  "/personaliza/configurador": {}
  "/pqrs": {}
  "/profile": {}
  "/register": {}
  "/reset-password": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/legal": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
