var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/finanzas/cash-flow/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~2122w._.js")
R.c("server/chunks/ssr/05kk_next_dist_0tx1gom._.js")
R.c("server/chunks/ssr/05kk_next_dist_esm_build_templates_app-page_0m58~-v.js")
R.c("server/chunks/ssr/[root-of-the-server]__05bb7z-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bi421v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__117hkad._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_0uqtttd._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_forbidden_0sjco.1.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_unauthorized_0t1cdw3.js")
R.c("server/chunks/ssr/apps_web_app_global-error_tsx_0t11m~q._.js")
R.c("server/chunks/ssr/_0ucum7h._.js")
R.c("server/chunks/ssr/_0~whrju._.js")
R.c("server/chunks/ssr/05kk_next_dist_0glp-rn._.js")
R.c("server/chunks/ssr/02dz_web__next-internal_server_app_dashboard_finanzas_cash-flow_page_actions_098djuk.js")
R.m(65615)
module.exports=R.m(65615).exports
