// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/(store)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/b2b/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/b2b">> = Specific
  const handler = {} as typeof import("../../app/(store)/b2b/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/beneficios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beneficios">> = Specific
  const handler = {} as typeof import("../../app/(store)/beneficios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/catalog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(store)/catalog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog">> = Specific
  const handler = {} as typeof import("../../app/(store)/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/checkout/confirmacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/confirmacion">> = Specific
  const handler = {} as typeof import("../../app/(store)/checkout/confirmacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../app/(store)/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/corporativo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/corporativo">> = Specific
  const handler = {} as typeof import("../../app/(store)/corporativo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/envios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/envios">> = Specific
  const handler = {} as typeof import("../../app/(store)/envios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/legal/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/cookies">> = Specific
  const handler = {} as typeof import("../../app/(store)/legal/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/legal/data-processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/data-processing">> = Specific
  const handler = {} as typeof import("../../app/(store)/legal/data-processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/legal/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/privacy">> = Specific
  const handler = {} as typeof import("../../app/(store)/legal/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/linea/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/linea/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(store)/linea/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/lineas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lineas">> = Specific
  const handler = {} as typeof import("../../app/(store)/lineas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(store)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/personaliza/configurador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personaliza/configurador">> = Specific
  const handler = {} as typeof import("../../app/(store)/personaliza/configurador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/personaliza/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personaliza">> = Specific
  const handler = {} as typeof import("../../app/(store)/personaliza/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/pqrs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pqrs">> = Specific
  const handler = {} as typeof import("../../app/(store)/pqrs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/(store)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/audit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/b2b/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/b2b">> = Specific
  const handler = {} as typeof import("../../app/dashboard/b2b/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/compras/facturacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/compras/facturacion">> = Specific
  const handler = {} as typeof import("../../app/dashboard/compras/facturacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/compras/recepcion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/compras/recepcion">> = Specific
  const handler = {} as typeof import("../../app/dashboard/compras/recepcion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/conocimiento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/conocimiento">> = Specific
  const handler = {} as typeof import("../../app/dashboard/conocimiento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/finanzas/cash-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finanzas/cash-flow">> = Specific
  const handler = {} as typeof import("../../app/dashboard/finanzas/cash-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/finanzas/nomina/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finanzas/nomina">> = Specific
  const handler = {} as typeof import("../../app/dashboard/finanzas/nomina/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/finanzas/opex/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finanzas/opex">> = Specific
  const handler = {} as typeof import("../../app/dashboard/finanzas/opex/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/finanzas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finanzas">> = Specific
  const handler = {} as typeof import("../../app/dashboard/finanzas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/logistica/envios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logistica/envios">> = Specific
  const handler = {} as typeof import("../../app/dashboard/logistica/envios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/logistica/insumos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logistica/insumos">> = Specific
  const handler = {} as typeof import("../../app/dashboard/logistica/insumos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/logistica/inventario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logistica/inventario">> = Specific
  const handler = {} as typeof import("../../app/dashboard/logistica/inventario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/logistica/inventario/salidas-no-comerciales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logistica/inventario/salidas-no-comerciales">> = Specific
  const handler = {} as typeof import("../../app/dashboard/logistica/inventario/salidas-no-comerciales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/logistica/proveedores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logistica/proveedores">> = Specific
  const handler = {} as typeof import("../../app/dashboard/logistica/proveedores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/orders">> = Specific
  const handler = {} as typeof import("../../app/dashboard/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/personalizaciones/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/personalizaciones/nueva">> = Specific
  const handler = {} as typeof import("../../app/dashboard/personalizaciones/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/personalizaciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/personalizaciones">> = Specific
  const handler = {} as typeof import("../../app/dashboard/personalizaciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/pqrs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pqrs">> = Specific
  const handler = {} as typeof import("../../app/dashboard/pqrs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/products/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/products/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products">> = Specific
  const handler = {} as typeof import("../../app/dashboard/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reportes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reportes">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reportes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/users">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/strategy/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/strategy/pricing">> = Specific
  const handler = {} as typeof import("../../app/dashboard/strategy/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proxy/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/proxy/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/v1/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/signout">> = Specific
  const handler = {} as typeof import("../../app/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(store)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(store)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(store)/legal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/legal">> = Specific
  const handler = {} as typeof import("../../app/(store)/legal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
