var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(store)/legal/cookies/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tphg5i._.js")
R.c("server/chunks/ssr/05kk_next_dist_0tx1gom._.js")
R.c("server/chunks/ssr/05kk_next_dist_esm_build_templates_app-page_0h0m1_2.js")
R.c("server/chunks/ssr/[root-of-the-server]__05bb7z-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bi421v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__117hkad._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_0uqtttd._.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_forbidden_0sjco.1.js")
R.c("server/chunks/ssr/05kk_next_dist_client_components_builtin_unauthorized_0t1cdw3.js")
R.c("server/chunks/ssr/apps_web_app_global-error_tsx_0t11m~q._.js")
R.c("server/chunks/ssr/apps_web_app_(store)_layout_tsx_0ajsdfs._.js")
R.c("server/chunks/ssr/apps_web_app_(store)_legal_layout_tsx_0b4obbt._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_(store)_legal_cookies_page_actions_0uf159u.js")
R.m(5326)
module.exports=R.m(5326).exports
